on:
  pull_request:
    types: [opened, synchronize]

jobs:
  evaluator_job:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Flake8 Linter Step
        uses: betrybe/flake8-linter-action@learn-274
        id: flake8_linter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.number }}
      - uses: actions/checkout@v2
      - name: Pytest Evaluator Step
        uses: betrybe/pytest-evaluator-action@v1
        id: pytest_evaluator
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.pytest_evaluator.outputs.result }}
          environment: staging
          pr-number: ${{ github.event.number }}
